### ISSUE TITLE
Instance (create) - Check IP

### ISSUE THREAD

**Issue by NikoLanzer** [dprandzioch/whitefuse-cm#10]
If you create a new instance, there should be another security check to prove that the chosen IP is free.

**Comment by dprandzioch** [comment]
When creating an instance, only IPs that are registered as unassigned can be used to create instances. Problems may occur when the instance is not created within whitefusecm and you want to create your new instance before the `UpdateHostStats` job arrives. 

Therefore we should ping in each UpdateHostStats iteration as well as immediatly before the container creation.

**Comment by dprandzioch** [comment]
Throws now a exception if the ip address is already in use.

![ipinuse](https://cloud.githubusercontent.com/assets/4499821/10584800/53a74dac-7694-11e5-8fa1-5cb6c1bab9c9.png)

IP address must be flagged so that it will be skipped when creating the next container.

**Comment by dprandzioch** [comment]
Solved & merged to develop. Will be releases in 0.7.0
