### ISSUE TITLE
Instances: List operating system

### ISSUE THREAD

**Issue by NikoLanzer** [dprandzioch/whitefuse-cm#11]
Another nice to have would be the listing of the used operating system in the "instances" overview.

**Comment by dprandzioch** [comment]
Is only possible if operating systems in flavors are supported. I will implement support for various templates and display their name in the instances overview. The template should be named after the operating system it is running anyway.

**Comment by dprandzioch** [comment]
wf_node_client has been enhanced (see https://github.com/dprandzioch/whitefuse-cm-node-api/commit/d8d3b5f0a5977665a2728f86c7451a04c4dc4684 ). master needs to be updated

**Comment by dprandzioch** [comment]
Master updated. Template column is now visible.

Every node may contain multiple container creation commands for the various templates. Those are exposed throught the API on `/v1/info` and stored on the master in a new model called `Template`. When creating a instance the user is prompted to choose a template matching one offered by the host. The associated command is then triggered on container creation.

Will be release in 0.7.0.
