### ISSUE TITLE
Instances: Check deleted Hostsystems 

### ISSUE THREAD

**Issue by NikoLanzer** [dprandzioch/whitefuse-cm#5]
If you delete a hostsystem manually not via the interface, the host should be deleted from the listed "Instances".

**Comment by dprandzioch** [comment]
Will be developed in branch feature-5-instance-sync

**Comment by dprandzioch** [comment]
Solved. Orphan instances will be removed within the UpdateHostStats job running every 15 min. Will be released in 0.7.0
