### ISSUE TITLE
Instances: Check inactive hosts

### ISSUE THREAD

**Issue by NikoLanzer** [dprandzioch/whitefuse-cm#8]
Sometime there could be virtual mashines that are curenntly switched off. Those hosts dont get inventoried or added to the "IP addresses".

**Comment by dprandzioch** [comment]
`UpdateHostStats::import_running_container` does not import those guests switched off right now. Should be changed. But this issue belongs to the node api.

**Comment by dprandzioch** [comment]
This is not that easy... When a guest is switched off and not created yet, we I can't get any usable information about the IP address used. I could parse the container configuration but as the container is not running this might be years old and could cause issues with running containers using the same IP address. Therefore I will close this issue. All containers needed in WhiteFuse should be started at least once for import. Afterwards they can be shut down and managed through wf.
