### ISSUE TITLE
Address pools - Add complete subnet

### ISSUE THREAD

**Issue by NikoLanzer** [dprandzioch/whitefuse-cm#9]
It would be a nice feature to add complete subnet to the "Address pools". The application should list all IP's and mark the IP's that are in use but not from one of the listed host systems.

**Comment by dprandzioch** [comment]
Solved. It's now possible to add complete subnets. A new job called CheckIpAddresses runs every 2 hours and checks, if ip addresses are usable. If a complete subnet is added, all addresses are invalid by default and checked afterwards. Single ip addresses are usable instantly. Addresses that are already in use (pingable using ICMP) are unusable anyway. Invalid addresses are greyed out.

![bildschirmfoto von 2015-10-21 20-29-50](https://cloud.githubusercontent.com/assets/4499821/10646642/7736c74c-7834-11e5-96b2-d344f2ebfeaa.png)
![bildschirmfoto von 2015-10-21 20-29-59](https://cloud.githubusercontent.com/assets/4499821/10646643/7737a202-7834-11e5-9c6b-268acc8160ce.png)

**Comment by dprandzioch** [comment]
Merged into develop.
